name: Build Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') 
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Build and test docker images
      env: 
        TAG: ${{ steps.get_version.outputs.VERSION }}
        REPO_SLUG: ${{ github.repository }}  
      run: ./build_platforms.sh
    - name: Run if tagged version
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') 
      env: 
        TAG: ${{ steps.get_version.outputs.VERSION }}
        REPO_SLUG: ${{ github.repository }}  
      run: echo run on tag $REPO_SLUG $TAG
