name: Build Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Always run
      run: echo "Always run"
    - name: Run if tagged version
      if: ${{ steps.get_version.outputs.VERSION }}
      env: 
        TRAVIS_TAG: ${{ steps.get_version.outputs.VERSION }}
      run: echo "Version: TRAVIS_TAG"
